version: "3.3"

services: 
    postgres:
      image: postgres:14
      restart: always
      environment: 
        - DATABASE_HOST=127.0.0.1
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=Pg301***
        - POSTGRES_DB=cultura
      ports: 
        - 5433:5432

    pgadmin:
      image: dpage/pgadmin4:7
      environment: 
        PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "Pg301***"
      ports:
        - "5050:80"
      depends_on: 
        - postgres